name: Build image & update ECS task
on:
  workflow_dispatch:
    branches:
      - blue-green
  push:
    branches:
      - blue-green
    paths:
      - 'application/**'
      - '.github/workflows/app.yml'
jobs:
  deploy_environment:
    defaults:
      run:
        working-directory: ./application    
    runs-on: ubuntu-latest
    environment:
      name: approval
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }} 
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      REPO_NAME: ${{ secrets.REPO_NAME }}
    steps:
    - uses: actions/checkout@v2  
    - name: run bash script
      run: |
        chmod +x deploy.sh
        ./deploy.sh
    - name: deploy to blue
      if: env.ENV_TO_DEPLOY == 'blue'
      run: make blue_deploy
    - name: deploy to green
      if: env.ENV_TO_DEPLOY == 'green'
      run: make green_deploy
