name: Deploy
on:
  workflow_dispatch:
    branches:
      - master
  push:
    branches:
      - master
    paths:
      - 'infrastructure/**'
      - '.github/workflows/main.yml'


jobs:
  terraform_plan:
    defaults:
      run:
        working-directory: infrastructure
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }} 
    steps:
    - uses: actions/checkout@v2
    - name: Terraform_Plan
      run: make run_plan       

  terraform_apply:
    defaults:
      run:
        working-directory: infrastructure
    runs-on: ubuntu-latest
    environment:
      name: approval
    needs: terraform_plan
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }} 
    steps:
    - uses: actions/checkout@v2
    - name: Terraform_Plan
      run: make run_plan
    - name: Terraform_Apply
      run: make run_apply  
    - name: "Run build-chain"
      id: build-chain
      uses: kiegroup/github-action-build-chain@v2.5
      with:
        definition-file: https://github.com/mayuthombre/weatherapp-infra/tree/master/.github/workflows/main.yaml

  docker_image:
    defaults:
      run:
        working-directory: ./application    
    runs-on: ubuntu-latest
    needs: terraform_apply
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }} 
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      REPO_NAME: ${{ secrets.REPO_NAME }}
    steps:
    - uses: actions/checkout@v2  
    - name: Login to ECR
      run: make login_ecr
    - name: Build docker image
      run: make build_image
    - name: Push image to ECR
      run: make push_image
    - name: Recreate ECS tasks
      run: make update_ecs
      
